### ISSUE TITLE
Extending message payloads

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-dataspace-protocol-base/dsp_best_practices#6]
- json schemas as foundation (see DSP spec, json schema `additionalProperties` are allowed)
  - json-schema-bound json-ld properties as extension (like "add a mandatory additional property to each `dcat:Dataset`")
  - further restrict the content of existing messages (like "all `dspace:providerId`s must confirm to a certain regex")

**Comment by juliapampus** [comment]
Citing myself for bullet 3 https://github.com/eclipse-dataspace-protocol-base/dsp_best_practices/discussions/4#discussioncomment-11541695

> We agreed in the past that DSP messages must not be profiled. Thus, defining the syntax of a property may be a recommendation by a specific dataspace but nothing that is part of the DSP or requested by the DSP as best practice.

Adding to point 3 that we should not explain how DCAT can be profiled, same as for ODRL.
